apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-checker"
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: "{{ .Release.Name }}-checker"
      restartPolicy: OnFailure
      containers:
      - name: checker
        image: '{{.Values.image.repository}}:{{.Values.image.tag|default .Chart.AppVersion}}'
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["/checker"]
        args:
          - "-namespace={{ .Release.Namespace }}"
          - "-name={{ .Release.Name }}"
          {{- if .Values.checker.disableCertManagerCheck }}
          - "-disable-cert-manager-check"
          {{- end }}
          {{- if .Values.checker.disableCertManagerInstall }}
          - "-disable-cert-manager-install"
          {{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
